[Update]
; Central catalog used by CCraft Launcher.
ManifestUrl=https://blitzpythoner.github.io/CCraft/launcher.ini

[Launcher]
Version=1.1
GameRoot=CCraft

[Releases]
Count=6

[Release1]
Version=Survival 1.0
DownloadUrl=https://blitzpythoner.github.io/CCraft/versions/CCraft_1.0.zip
Sha256=7af0462df0a770e558604332f41c59a2c5a42f95d9fa300fea871cb3812ff7e0

[Release2]
Version=Survival 1.1
DownloadUrl=https://blitzpythoner.github.io/CCraft/versions/CCraft_1.1.zip
Sha256=4bc6a0d1c920574bf82ca08822d07c097535096c51ab3f638a60d87d7382ad4d

[Release3]
Version=Survival 1.2
DownloadUrl=https://blitzpythoner.github.io/CCraft/versions/CCraft_1.2.zip
Sha256=df99f2974472dad478637c70d54942a030b0573e99952b5308f8a8da49bf6c06

[Release4]
Version=Survival 1.3
DownloadUrl=https://blitzpythoner.github.io/CCraft/versions/CCraft_1.3.zip
Sha256=0c07f0aee76ceb62e086cdb9d7eccbc9c9ef262370fb49b097d465e602738128

[Release5]
Version=Adventure 1.4
DownloadUrl=https://blitzpythoner.github.io/CCraft/versions/CCraft_1.4.zip
Sha256=6b8eaeb134ea7581bd005a8e51aa9464d53d60241cd3c6a0227cc0befc359a52

[Release6]
Version=Adventure 1.5
DownloadUrl=https://blitzpythoner.github.io/CCraft/versions/CCraft_1.5.zip
Sha256=959e77509f7a79d72888f136c6a37e73a6ef6a7e0195e3a74825c4294f6f2577
